services:
  postgres:
    container_name: brigthe_postgres
    hostname: postgres
    image: 'postgres:15'
    environment:
      POSTGRES_DB: brighte
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - brighte_db:/var/lib/postgresql/data
    networks:
      - brighte_network

  # Comment when running directly with Node
  ### START OF SECTION TO COMMENT ###
  backend:
    container_name: backend
    hostname: backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    restart: always
    networks:
      - brighte_network
  ### END OF SECTION TO COMMENT ###

volumes:
  brighte_db:

networks:
  brighte_network:
