services:
  postgres:
    container_name: db_test
    hostname: postgres
    image: 'postgres:15'
    environment:
      POSTGRES_DB: brighte
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - brighte_test_db:/var/lib/postgresql/data

volumes:
  brighte_test_db:
